<h3 style="color:orange; text-align:center;"> Mathematics for ML [Algorithms] </h3>

From:MATHEMATICS FOR MACHINE LEARNING

By: Mohamed Aazi

--------------------------------------

<h4 style="color:cyan;">1. LINEAR ALGEBRA </h4>

<h5 style="color:orange;"> 1.1 Vector addition </h5>

In [3]:
import numpy as np

u = np.array([1,2])
v = np.array([3,4])
print(u+v)

[4 6]


<h5 style="color:orange;"> 1.2 Scalar multiplication of a vector </h5>

In [5]:
import numpy as np

alpha = 3
v = np.array([2,-1])
print(alpha * v)

[ 6 -3]


<h5 style="color:orange;"> 1.3 Dot product </h5>

In [6]:
import numpy as np

u = np.array([1,2])
v = np.array([3,4])
dot_product = np.dot(u,v)
print(dot_product)


11


<h5 style="color:orange;"> 1.4 Cross product (3D) </h5>

In [7]:
import numpy as np
u = np.array([1,0,0])
v = np.array([0,1,0])
cross_product = np.cross(u,v)
print(cross_product)

[0 0 1]


<h5 style="color:orange;"> 1.5 Norm of a vector (Euclidean) </h5>

In [8]:
import numpy as np
v = np.array([3,4])
norm = np.linalg.norm(v)
print(norm)

5.0


<h5 style="color:orange;"> 1.6 Orthogonality condition </h5>

In [9]:
import numpy as np
u = np.array([1,2])
v = np.array([-2,1])
dot_product = np.dot(u,v)
print(dot_product)

0


<h5 style="color:orange;"> 1.7 Matrix addition </h5>

In [14]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(A + B)

[[ 6  8]
 [10 12]]


<h5 style="color:orange;"> 1.8 Matrix scalar multiplication </h5>

In [17]:
import numpy as np
alpha = 2
A = np.array([[1,2],[3,4]])
print(alpha * A)

[[2 4]
 [6 8]]


<h5 style="color:orange;"> 1.9 Matrix-vector multiplication </h5>

In [11]:
import numpy as np
A = np.array([[1,2],[3,4]])
x = np.array([5,6])

print("Right side multiplication:")
print(A @ x)
print(np.dot(A,x))
print("Left side multiplication:")
print(x @ A)

Right side multiplication:
[17 39]
[17 39]
Left side multiplication:
[23 34]


<h5 style="color:orange;"> 1.10 Matrix multiplication </h5>

In [14]:
import numpy as np
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("A by the left side")
print(A @ B)
print("B by the left side")
print(B @ A)

A by the left side
[[19 22]
 [43 50]]
B by the left side
[[23 34]
 [31 46]]


<h5 style="color:orange;"> 1.11 Transpose of a Matrix </h5>

In [18]:
import numpy as np
A = np.array([[1,2],[3,4]])
print(A.T)

[[1 3]
 [2 4]]


<h5 style="color:orange;"> 1.12 Determinant of a 2x2 matrix </h5>

In [16]:
import numpy as np
A = np.array([[3,8],[4,6]])
np.linalg.det(A)

np.float64(-14.000000000000004)

<h5 style="color:orange;"> 1.13 Inverse of a 2x2 matrix </h5>

In [14]:
import numpy as np
A = np.array([[3,8],[4,6]])
A_inv = np.linalg.inv(A)
print("test")
print(A @ A_inv)

test
[[1. 0.]
 [0. 1.]]


<h5 style="color:orange;"> 1.14 Cramer's rule </h5>

Cramer's rule solve system of equations Ax = b

\begin{align}
\text{Example: For } \mathbf{A} &= \begin{bmatrix} 2 & 1 \\ 1 & 3 \end{bmatrix} \text{ and } \mathbf{b} = \begin{bmatrix} 5 \\ 7 \end{bmatrix}, \\[1em]
\mathbf{A}_1 &= \begin{bmatrix} 5 & 1 \\ 7 & 3 \end{bmatrix}, \quad \mathbf{A}_2 = \begin{bmatrix} 2 & 5 \\ 1 & 7 \end{bmatrix} \\[1em]
\text{and } \det(\mathbf{A}) &= 5, \text{ so } x_1 = \frac{\det(\mathbf{A}_1)}{\det(\mathbf{A})}, \quad x_2 = \frac{\det(\mathbf{A}_2)}{\det(\mathbf{A})}
\end{align}

In [10]:
import numpy as np

A = np.array([[2,1],[1,3]])
b = np.array([5,7])
det_A = np.linalg.det(A)
x = [np.linalg.det(np.column_stack([b if j == i else A[:,j] for j in range(A.shape[1])])) / det_A for i in range(A.shape[1])]
print(np.round(x,3))

[1.6 1.8]


In [12]:
def solve_cramer_rule(A, b):
    """
    Solve linear system Ax = b using Cramer's rule.
    
    Parameters:
    A (np.array): Coefficient matrix (n x n)
    b (np.array): Right-hand side vector (n,)
    
    Returns:
    np.array: Solution vector x
    """
    # Calculate determinant of coefficient matrix A
    det_A = np.linalg.det(A)
    
    # Check if system has unique solution
    if np.abs(det_A) < 1e-10:
        raise ValueError("Matrix A is singular - no unique solution exists")
    
    # Get number of variables
    n = A.shape[1]
    
    # Initialize solution vector
    x = np.zeros(n)
    
    # Apply Cramer's rule: x[i] = det(A_i) / det(A)
    for i in range(n):
        # Create matrix A_i by replacing column i with vector b
        A_i = A.copy()
        A_i[:, i] = b
        
        # Calculate x[i] using Cramer's rule
        x[i] = np.linalg.det(A_i) / det_A
    
    return x

# Example usage
A = np.array([[2, 1], [1, 3]])
b = np.array([5, 7])
solution = solve_cramer_rule(A, b)
print("Solution:", solution)
# Test
A @ x

Solution: [1.6 1.8]


array([5., 7.])

<h5 style="color:orange;"> 1.15 Inverse of a square matrix </h5>

In [ ]:
import numpy as np
A = np.array([[4,7],[2,6]])
A_inv = np.linalg.inv(A)
print(A_inv)
print("test")
print(np.round(A @ A_inv, 6))

[[ 0.6 -0.7]
 [-0.2  0.4]]
test
[[ 1.  0.]
 [-0.  1.]]


<h5 style="color:orange;"> 1.16 Determinant of a triangular matrix </h5>

$$\textcolor{cyan}{\det(\mathbf{A}) = \prod_{i=1}^{n} a_{ii}}$$

In [4]:
import numpy as np
A = np.array([[2,1,0],[0,3,4],[0,0,5]])
det_A = np.prod(np.diag(A))
print(det_A)


30


<h5 style="color:orange;"> 1.17 Rank-nullity theorem </h5>

Rank = # of independent columns (or rows)

Nullity = # of solutions to Ax=0 (free variables)

Theorem :

rank(A) + nullity(A) = n (number of columns)

In [5]:
import numpy as np

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
rank_A = np.linalg.matrix_rank(A)
print(rank_A)
nullity = A.shape[1] - rank_A
print(nullity)

2
1


<h5 style="color:orange;"> 1.18 Hadarman (elementwise) product </h5>